version: "3.7"

networks:
  postgres-db:
    external: true
  server:
    driver: bridge
  client:
    driver: bridge

services:
  node:
    image: tamanit/time_cafe_manager_node:latest
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
    networks:
      - client

  api:
    image: tamanit/time_cafe_manager_api:latest
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
    networks:
      - postgres-db
      - server

  nginx:
    image: tamanit/time_cafe_manager_nginx:latest
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
    networks:
      - client
      - server