version: "3.7"

services:
  node:
    build:
      context: ./
      dockerfile: deploy/docker/node.Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./app:/app
    networks:
      - db-network
      - minio-network

  db:
    image: postgres:15.1
    shm_size: 256mb
    restart: unless-stopped
    volumes:
      - ./volumes/db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db-network
    environment:
      POSTGRES_DB: "tutorhelper.ru"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./volumes/minio-volume:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-network

networks:
  db-network:
    driver: bridge
  minio-network:
    driver: bridge